# Generated by Django 5.2.14 on 2026-05-29 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BuildState",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "singleton_id",
                    models.PositiveSmallIntegerField(
                        default=1, editable=False, unique=True
                    ),
                ),
                ("is_dirty", models.BooleanField(default=False)),
                ("dirty_since", models.DateTimeField(blank=True, null=True)),
                ("last_built", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "build state",
                "verbose_name_plural": "build state",
            },
        ),
    ]
