# Generated by Django 5.2.14 on 2026-05-29 09:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Edition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(blank=True, max_length=200)),
                ("catalogue_number", models.CharField(blank=True, max_length=200)),
                ("record_label", models.CharField(blank=True, max_length=200)),
                ("year", models.IntegerField(blank=True, null=True)),
                (
                    "media",
                    models.CharField(
                        blank=True,
                        help_text="e.g. CD, 2xCD, Vinyl, CD-R.",
                        max_length=100,
                    ),
                ),
                ("purchase_link", models.URLField(blank=True)),
                ("display_order", models.IntegerField(default=0)),
                (
                    "mbid",
                    models.UUIDField(
                        blank=True, help_text="MusicBrainz release id.", null=True
                    ),
                ),
            ],
            options={
                "ordering": ["display_order", "-year", "catalogue_number"],
            },
        ),
        migrations.CreateModel(
            name="ReleaseType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("display_order", models.IntegerField(default=0)),
            ],
            options={
                "verbose_name": "release type",
                "ordering": ["display_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="Artist",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.SlugField(blank=True, max_length=200, unique=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=200)),
                ("biography", models.TextField(blank=True)),
                (
                    "is_alias",
                    models.BooleanField(
                        default=False,
                        help_text="True for a Fluke alias / side-project.",
                    ),
                ),
                (
                    "primary_artist",
                    models.ForeignKey(
                        blank=True,
                        help_text="For an alias, the primary act it belongs to (usually Fluke).",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="aliases",
                        to="discography.artist",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="CoverImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                ("display_name", models.CharField(blank=True, max_length=100)),
                ("image", models.ImageField(blank=True, upload_to="covers/")),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("front", "Front"),
                            ("back", "Back"),
                            ("cd", "CD"),
                            ("inlay", "Inlay"),
                            ("booklet", "Booklet"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=20,
                    ),
                ),
                ("alt_text", models.CharField(blank=True, max_length=300)),
                ("source_url", models.URLField(blank=True)),
                ("display_order", models.IntegerField(default=0)),
                (
                    "edition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="covers",
                        to="discography.edition",
                    ),
                ),
            ],
            options={
                "ordering": ["display_order", "id"],
            },
        ),
        migrations.CreateModel(
            name="Lyric",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=300)),
                ("lyrics", models.TextField(blank=True)),
                ("comments", models.TextField(blank=True)),
                (
                    "artist",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="lyrics",
                        to="discography.artist",
                    ),
                ),
            ],
            options={
                "ordering": ["title"],
            },
        ),
        migrations.CreateModel(
            name="Release",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.SlugField(blank=True, max_length=200, unique=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                (
                    "seo_title",
                    models.CharField(
                        blank=True,
                        help_text="Overrides the <title>; defaults to the title.",
                        max_length=200,
                    ),
                ),
                (
                    "meta_description",
                    models.CharField(
                        blank=True,
                        help_text="Search-result snippet; ~150–160 chars ideal.",
                        max_length=300,
                    ),
                ),
                (
                    "canonical_url",
                    models.URLField(
                        blank=True, help_text="Optional canonical override."
                    ),
                ),
                ("og_title", models.CharField(blank=True, max_length=200)),
                ("og_description", models.CharField(blank=True, max_length=300)),
                (
                    "og_image",
                    models.ImageField(
                        blank=True,
                        help_text="Auto-generated when blank (where supported).",
                        upload_to="og/",
                    ),
                ),
                (
                    "noindex",
                    models.BooleanField(
                        default=False,
                        help_text="Exclude from sitemap and add a noindex tag.",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("year", models.IntegerField(blank=True, null=True)),
                ("order", models.IntegerField(default=0)),
                ("purchase_link", models.URLField(blank=True)),
                (
                    "mbid",
                    models.UUIDField(
                        blank=True, help_text="MusicBrainz release-group id.", null=True
                    ),
                ),
                ("is_published", models.BooleanField(default=True)),
                (
                    "artist",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="releases",
                        to="discography.artist",
                    ),
                ),
                (
                    "type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="releases",
                        to="discography.releasetype",
                    ),
                ),
            ],
            options={
                "ordering": ["-year", "order", "name"],
            },
        ),
        migrations.AddField(
            model_name="edition",
            name="release",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="editions",
                to="discography.release",
            ),
        ),
        migrations.CreateModel(
            name="Track",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=300)),
                ("track_number", models.CharField(blank=True, max_length=20)),
                (
                    "mix_info",
                    models.CharField(
                        blank=True,
                        help_text="e.g. Instrumental, Radio Edit.",
                        max_length=200,
                    ),
                ),
                (
                    "length",
                    models.CharField(blank=True, help_text="m:ss", max_length=20),
                ),
                ("sample", models.FileField(blank=True, upload_to="samples/")),
                ("sample_source_url", models.URLField(blank=True)),
                ("display_order", models.IntegerField(default=0)),
                ("mbid", models.UUIDField(blank=True, null=True)),
                ("recording_mbid", models.UUIDField(blank=True, null=True)),
                (
                    "edition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tracks",
                        to="discography.edition",
                    ),
                ),
                (
                    "lyric",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tracks",
                        to="discography.lyric",
                    ),
                ),
                (
                    "remixer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="remixes",
                        to="discography.artist",
                    ),
                ),
            ],
            options={
                "ordering": ["display_order", "track_number"],
            },
        ),
    ]
