# Generated by Django 5.2.14 on 2026-05-30 15:30

import apps.discography.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("discography", "0002_alter_release_seo_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="track",
            name="sample",
            field=models.FileField(
                blank=True, upload_to=apps.discography.storage.uuid_upload_to("samples")
            ),
        ),
    ]
