# Generated by Django 5.2.14 on 2026-05-31 14:04

from django.db import migrations, models
from django.db.models import Q


def show_existing_aliases(apps, schema_editor):
    """Keep the current homepage hero by surfacing existing aliases / side-projects.

    An artist counts as an alias/project if it is flagged ``is_alias`` or points at
    a ``primary_artist`` (some legacy rows set one but not the other).
    """
    Artist = apps.get_model("discography", "Artist")
    Artist.objects.filter(Q(is_alias=True) | Q(primary_artist__isnull=False)).update(
        appears_on_homepage=True
    )


class Migration(migrations.Migration):

    dependencies = [
        ("discography", "0004_lyric_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="artist",
            name="appears_on_homepage",
            field=models.BooleanField(
                default=False,
                help_text="Show in the homepage hero list of aliases & other projects (Fluke always leads, regardless of this).",
            ),
        ),
        migrations.RunPython(show_existing_aliases, migrations.RunPython.noop),
    ]
