# Generated by Django 5.2.14 on 2026-06-06 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("discography", "0005_artist_appears_on_homepage"),
    ]

    operations = [
        migrations.AddField(
            model_name="artist",
            name="canonical_url",
            field=models.URLField(blank=True, help_text="Optional canonical override."),
        ),
        migrations.AddField(
            model_name="artist",
            name="meta_description",
            field=models.CharField(
                blank=True,
                help_text="Search-result snippet; ~150–160 chars ideal.",
                max_length=300,
            ),
        ),
        migrations.AddField(
            model_name="artist",
            name="noindex",
            field=models.BooleanField(
                default=False, help_text="Exclude from sitemap and add a noindex tag."
            ),
        ),
        migrations.AddField(
            model_name="artist",
            name="og_description",
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name="artist",
            name="og_image",
            field=models.ImageField(
                blank=True,
                help_text="Auto-generated when blank (where supported).",
                upload_to="og/",
            ),
        ),
        migrations.AddField(
            model_name="artist",
            name="og_title",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="artist",
            name="seo_title",
            field=models.CharField(
                blank=True,
                help_text="Overrides the HTML page title; defaults to the title.",
                max_length=200,
            ),
        ),
        migrations.AddField(
            model_name="lyric",
            name="canonical_url",
            field=models.URLField(blank=True, help_text="Optional canonical override."),
        ),
        migrations.AddField(
            model_name="lyric",
            name="meta_description",
            field=models.CharField(
                blank=True,
                help_text="Search-result snippet; ~150–160 chars ideal.",
                max_length=300,
            ),
        ),
        migrations.AddField(
            model_name="lyric",
            name="noindex",
            field=models.BooleanField(
                default=False, help_text="Exclude from sitemap and add a noindex tag."
            ),
        ),
        migrations.AddField(
            model_name="lyric",
            name="og_description",
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name="lyric",
            name="og_image",
            field=models.ImageField(
                blank=True,
                help_text="Auto-generated when blank (where supported).",
                upload_to="og/",
            ),
        ),
        migrations.AddField(
            model_name="lyric",
            name="og_title",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="lyric",
            name="seo_title",
            field=models.CharField(
                blank=True,
                help_text="Overrides the HTML page title; defaults to the title.",
                max_length=200,
            ),
        ),
    ]
