# Generated by Django 5.2.14 on 2026-06-07 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("discography", "0006_artist_lyric_seo_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="release",
            name="featured_artists",
            field=models.ManyToManyField(
                blank=True,
                help_text="Guest/featured artists, shown as “(feat. …)” after the title.",
                related_name="featured_on",
                to="discography.artist",
            ),
        ),
    ]
