# Generated by Django 5.2.14 on 2026-06-16 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("discography", "0007_release_featured_artists"),
    ]

    operations = [
        migrations.AddField(
            model_name="release",
            name="additional_artists",
            field=models.ManyToManyField(
                blank=True,
                help_text="Other acts credited alongside the primary artist (e.g. a “vs.” collaboration). Shown comma-separated after the primary artist; the primary artist still owns the URL and grouping.",
                related_name="additional_releases",
                to="discography.artist",
            ),
        ),
    ]
