# Generated by Django 5.2.14 on 2026-06-19 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("discography", "0008_release_additional_artists"),
    ]

    operations = [
        migrations.AddField(
            model_name="release",
            name="hide_artist_list",
            field=models.BooleanField(
                default=False,
                help_text="Drop the '(artist, …)' suffix after the title on the discography listing.",
                verbose_name="Do not display additional artist list on discography page",
            ),
        ),
    ]
