# Generated by Django 5.2.14 on 2026-06-19 09:42

from django.db import migrations, models


def copy_remixer_to_remixers(apps, schema_editor):
    """Carry each track's single remixer over into the new multi-select."""
    Track = apps.get_model("discography", "Track")
    for track in Track.objects.filter(remixer__isnull=False).iterator():
        track.remixers.add(track.remixer_id)


def copy_remixers_back_to_remixer(apps, schema_editor):
    """Reverse: keep the first remixer as the single FK."""
    Track = apps.get_model("discography", "Track")
    for track in Track.objects.iterator():
        first = track.remixers.first()
        if first is not None:
            track.remixer = first
            track.save(update_fields=["remixer"])


class Migration(migrations.Migration):

    dependencies = [
        ("discography", "0009_release_hide_artist_list"),
    ]

    operations = [
        # Add the new M2M first, copy the existing single remixer into it, then
        # drop the old FK — so existing data is preserved.
        migrations.AddField(
            model_name="track",
            name="remixers",
            field=models.ManyToManyField(
                blank=True,
                help_text="Artist(s) who remixed this track.",
                related_name="remixed_tracks",
                to="discography.artist",
            ),
        ),
        migrations.RunPython(copy_remixer_to_remixers, copy_remixers_back_to_remixer),
        migrations.RemoveField(
            model_name="track",
            name="remixer",
        ),
    ]
