# Generated by Django 5.2.14 on 2026-06-19 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("discography", "0010_remove_track_remixer_track_remixers"),
    ]

    operations = [
        migrations.AddField(
            model_name="artist",
            name="is_person",
            field=models.BooleanField(
                default=False,
                help_text="An individual person (schema.org Person) rather than a band/group (MusicGroup). Affects the structured-data type in markup.",
                verbose_name="Is a person",
            ),
        ),
    ]
