# Generated by Django 5.2.14 on 2026-06-21 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("discography", "0011_artist_is_person"),
    ]

    operations = [
        migrations.AddField(
            model_name="edition",
            name="notes",
            field=models.TextField(
                blank=True,
                help_text="A few words about this specific edition (e.g. how rare it is, the source for the entry). Shown under the edition heading when expanded.",
            ),
        ),
    ]
