# Generated by Django 5.2.14 on 2026-06-21 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("discography", "0012_edition_notes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="edition",
            name="notes",
            field=models.TextField(
                blank=True,
                help_text="Rich text (HTML), edited with TinyMCE. A few words about this specific edition (e.g. how rare it is, the source for the entry). Shown under the edition heading when expanded.",
            ),
        ),
    ]
