# Generated by Django 5.2.14 on 2026-06-22 08:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("discography", "0013_alter_edition_notes"),
    ]

    operations = [
        migrations.AddField(
            model_name="track",
            name="artist",
            field=models.ForeignKey(
                blank=True,
                help_text="Performing artist for this track (useful on Various Artists comps). Blank inherits the release's artist; that inherited artist isn't repeated on each track, and “Various Artists” is never shown.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="performed_tracks",
                to="discography.artist",
            ),
        ),
    ]
