"""Behavioural tests for discography model methods."""

import pytest

from apps.discography.models import (
    Artist,
    Edition,
    Lyric,
    Release,
    ReleaseType,
    Track,
)

pytestmark = pytest.mark.django_db


def _release(name="Risotto", artist=None, **kwargs):
    artist = artist or Artist.objects.create(name="Fluke")
    rtype, _ = ReleaseType.objects.get_or_create(name="Album")
    return Release.objects.create(name=name, artist=artist, type=rtype, **kwargs)


# --- Artist alias grouping -------------------------------------------------

def test_canonical_returns_self_for_a_primary_artist():
    fluke = Artist.objects.create(name="Fluke")
    assert fluke.canonical == fluke


def test_canonical_returns_primary_for_an_alias():
    fluke = Artist.objects.create(name="Fluke")
    pie = Artist.objects.create(name="2 Bit Pie", is_alias=True, primary_artist=fluke)
    assert pie.canonical == fluke


def test_artist_get_absolute_url():
    pie = Artist.objects.create(name="2 Bit Pie")
    assert pie.get_absolute_url() == "/discography/2-bit-pie/"


# --- Release ---------------------------------------------------------------

def test_release_get_absolute_url_uses_artist_and_release_slugs():
    fluke = Artist.objects.create(name="Fluke")
    release = _release(name="Risotto", artist=fluke)
    assert release.get_absolute_url() == "/discography/fluke/risotto/"


def test_release_published_manager_excludes_unpublished():
    visible = _release(name="Risotto")
    _release(name="Hidden", artist=visible.artist, is_published=False)
    slugs = set(Release.objects.published().values_list("slug", flat=True))
    assert "risotto" in slugs
    assert "hidden" not in slugs


# --- Release display title -------------------------------------------------

def test_release_display_title_is_plain_name_for_fluke():
    fluke = Artist.objects.create(name="Fluke")
    release = _release(name="Risotto", artist=fluke)
    assert release.display_title == "Risotto"


def test_release_display_title_appends_artist_for_an_alias():
    fluke = Artist.objects.create(name="Fluke")
    yuki = Artist.objects.create(name="Yuki", is_alias=True, primary_artist=fluke)
    release = _release(name="Dark Like Snow", artist=yuki)
    assert release.display_title == "Dark Like Snow (Yuki)"


def test_release_display_title_appends_artist_for_non_alias_non_fluke():
    anaxaton6 = Artist.objects.create(name="ANAXATON6")
    release = _release(name="Juju Grid EP", artist=anaxaton6)
    assert release.display_title == "Juju Grid EP (ANAXATON6)"


# --- Slug auto-generation (via core.SluggedModel) --------------------------

def test_release_slug_autogenerated_and_unique():
    fluke = Artist.objects.create(name="Fluke")
    first = _release(name="Tosh", artist=fluke)
    second = _release(name="Tosh", artist=fluke)
    assert first.slug == "tosh"
    assert second.slug == "tosh-2"


# --- Lyric ------------------------------------------------------------------

def test_lyric_get_absolute_url_uses_slug():
    lyric = Lyric.objects.create(title="You Got Me")
    assert lyric.get_absolute_url() == "/lyrics/you-got-me/"


def test_lyric_slug_autogenerated_and_unique():
    first = Lyric.objects.create(title="Bliss")
    second = Lyric.objects.create(title="Bliss")
    assert first.slug == "bliss"
    assert second.slug == "bliss-2"


# --- Track display title ---------------------------------------------------

def _track(name="Blue", mix_info=""):
    edition = Edition.objects.create(release=_release())
    return Track.objects.create(edition=edition, name=name, mix_info=mix_info)


def test_track_display_title_plain():
    assert _track(name="Blue").display_title == "Blue"


def test_track_display_title_with_mix_info():
    assert _track(name="Blue", mix_info="Instrumental").display_title == "Blue (Instrumental)"
