# Generated by Django 5.2.14 on 2026-05-29 09:08

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("discography", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ResourceSubcategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.SlugField(blank=True, max_length=200, unique=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=100)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("official", "Official Resources"),
                            ("fan", "Fan Remixes & Resources"),
                        ],
                        default="official",
                        max_length=20,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("display_order", models.IntegerField(default=0)),
            ],
            options={
                "verbose_name_plural": "resource subcategories",
                "ordering": ["kind", "display_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="Resource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.SlugField(blank=True, max_length=200, unique=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                (
                    "seo_title",
                    models.CharField(
                        blank=True,
                        help_text="Overrides the <title>; defaults to the title.",
                        max_length=200,
                    ),
                ),
                (
                    "meta_description",
                    models.CharField(
                        blank=True,
                        help_text="Search-result snippet; ~150–160 chars ideal.",
                        max_length=300,
                    ),
                ),
                (
                    "canonical_url",
                    models.URLField(
                        blank=True, help_text="Optional canonical override."
                    ),
                ),
                ("og_title", models.CharField(blank=True, max_length=200)),
                ("og_description", models.CharField(blank=True, max_length=300)),
                (
                    "og_image",
                    models.ImageField(
                        blank=True,
                        help_text="Auto-generated when blank (where supported).",
                        upload_to="og/",
                    ),
                ),
                (
                    "noindex",
                    models.BooleanField(
                        default=False,
                        help_text="Exclude from sitemap and add a noindex tag.",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("official", "Official Resources"),
                            ("fan", "Fan Remixes & Resources"),
                        ],
                        default="official",
                        max_length=20,
                    ),
                ),
                ("description", models.TextField(blank=True, help_text="Markdown.")),
                (
                    "contributor",
                    models.CharField(
                        blank=True, help_text="Fan / remixer credit.", max_length=200
                    ),
                ),
                ("source_attribution", models.CharField(blank=True, max_length=300)),
                ("license", models.CharField(blank=True, max_length=200)),
                ("recorded_date", models.DateField(blank=True, null=True)),
                ("released_date", models.DateField(blank=True, null=True)),
                (
                    "uploaded_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="When this was added to the site.",
                    ),
                ),
                (
                    "external_url",
                    models.URLField(
                        blank=True, help_text="Used when not hosted on-site."
                    ),
                ),
                ("is_published", models.BooleanField(default=False)),
                (
                    "artist",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="resources",
                        to="discography.artist",
                    ),
                ),
                (
                    "related_edition",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="resources",
                        to="discography.edition",
                    ),
                ),
                (
                    "related_release",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="resources",
                        to="discography.release",
                    ),
                ),
                (
                    "subcategory",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="resources",
                        to="resources.resourcesubcategory",
                    ),
                ),
            ],
            options={
                "ordering": ["-uploaded_at", "title"],
            },
        ),
        migrations.CreateModel(
            name="ResourceFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                ("file", models.FileField(upload_to="resources/")),
                ("original_filename", models.CharField(blank=True, max_length=300)),
                (
                    "file_kind",
                    models.CharField(
                        choices=[
                            ("audio", "Audio"),
                            ("archive", "Archive"),
                            ("image", "Image"),
                            ("video", "Video"),
                            ("document", "Document"),
                        ],
                        default="audio",
                        max_length=20,
                    ),
                ),
                ("byte_size", models.BigIntegerField(default=0)),
                ("mime_type", models.CharField(blank=True, max_length=100)),
                ("duration", models.DurationField(blank=True, null=True)),
                (
                    "checksum",
                    models.CharField(
                        blank=True, help_text="sha256, for dedupe.", max_length=64
                    ),
                ),
                ("display_order", models.IntegerField(default=0)),
                (
                    "resource",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="files",
                        to="resources.resource",
                    ),
                ),
            ],
            options={
                "ordering": ["display_order", "id"],
            },
        ),
    ]
