# Generated by Django 5.2.14 on 2026-05-30 08:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_alter_post_seo_title"),
        ("resources", "0002_alter_resource_seo_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="resource",
            name="related_post",
            field=models.ForeignKey(
                blank=True,
                help_text="Optional blog post that announces or discusses this resource.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="resources",
                to="blog.post",
            ),
        ),
    ]
