# Generated by Django 5.2.14 on 2026-06-01 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resources", "0003_resource_related_post"),
    ]

    operations = [
        migrations.AddField(
            model_name="resource",
            name="snippet",
            field=models.CharField(
                blank=True,
                help_text="One-line description shown in resource listings.",
                max_length=255,
                verbose_name="Snippet explanation",
            ),
        ),
    ]
