# Generated by Django 5.2.14 on 2026-06-15 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resources", "0004_resource_snippet"),
    ]

    operations = [
        migrations.AddField(
            model_name="resource",
            name="recorded_precision",
            field=models.CharField(
                choices=[("year", "Year"), ("month", "Month"), ("day", "Day")],
                default="day",
                max_length=5,
            ),
        ),
    ]
