# Generated by Django 5.2.14 on 2026-06-15 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resources", "0005_resource_recorded_precision"),
    ]

    operations = [
        migrations.AddField(
            model_name="resourcesubcategory",
            name="snippet_phrase",
            field=models.CharField(
                blank=True,
                help_text="How a resource in this subcategory is described in its auto snippet, after the kind word — e.g. “music video” gives “Official music video”. Leave blank to derive it automatically.",
                max_length=100,
            ),
        ),
    ]
