# Generated by Django 5.2.14 on 2026-06-16 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("discography", "0008_release_additional_artists"),
        ("resources", "0006_resourcesubcategory_snippet_phrase"),
    ]

    operations = [
        migrations.AddField(
            model_name="resource",
            name="additional_artists",
            field=models.ManyToManyField(
                blank=True,
                help_text="Other artists credited alongside the primary artist (shown comma-separated wherever the artist appears).",
                related_name="additional_resources",
                to="discography.artist",
            ),
        ),
        migrations.AddField(
            model_name="resourcefile",
            name="external_url",
            field=models.URLField(
                blank=True,
                help_text="Link to an off-site copy instead of uploading a file. Provide either a file or a URL.",
            ),
        ),
        migrations.AlterField(
            model_name="resourcefile",
            name="file",
            field=models.FileField(blank=True, upload_to="resources/"),
        ),
    ]
