# Generated by Django 5.2.14 on 2026-06-24 20:05

import apps.resources.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resources", "0007_resource_additional_artists_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="resourcefile",
            name="is_locked",
            field=models.BooleanField(
                default=False,
                help_text="Archived: stored but downloadable only by staff. The file is moved to private storage and is not publicly reachable.",
            ),
        ),
        migrations.AddField(
            model_name="resourcefile",
            name="locked_file",
            field=models.FileField(
                blank=True,
                help_text="Internal: holds the bytes while locked. Managed automatically.",
                storage=apps.resources.storage.PrivateMediaStorage(),
                upload_to="resources/",
            ),
        ),
        migrations.AddField(
            model_name="resourcefile",
            name="preview_image",
            field=models.ImageField(
                blank=True,
                help_text="Optional public preview shown for a locked file.",
                upload_to="resources/previews/",
            ),
        ),
    ]
