# Generated by Django 5.2.14 on 2026-06-24 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resources", "0008_resourcefile_locking"),
    ]

    operations = [
        migrations.AddField(
            model_name="resource",
            name="article_authors",
            field=models.CharField(
                blank=True, help_text="Article author(s), free text.", max_length=300
            ),
        ),
        migrations.AddField(
            model_name="resource",
            name="article_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="resource",
            name="article_date_precision",
            field=models.CharField(
                choices=[("year", "Year"), ("month", "Month"), ("day", "Day")],
                default="day",
                max_length=5,
            ),
        ),
        migrations.AddField(
            model_name="resource",
            name="article_url",
            field=models.URLField(blank=True, help_text="Link to the article online."),
        ),
        migrations.AddField(
            model_name="resource",
            name="page_numbers",
            field=models.CharField(
                blank=True, help_text='e.g. "pp. 34–37".', max_length=50
            ),
        ),
        migrations.AddField(
            model_name="resource",
            name="publication_title",
            field=models.CharField(
                blank=True, help_text="Magazine or journal title.", max_length=200
            ),
        ),
        migrations.AddField(
            model_name="resource",
            name="purchase_url",
            field=models.URLField(blank=True, help_text="Where to buy the issue."),
        ),
    ]
