# Generated by Django 5.2.14 on 2026-07-01 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resources", "0009_resource_print_metadata"),
    ]

    operations = [
        migrations.AlterField(
            model_name="resource",
            name="purchase_url",
            field=models.URLField(
                blank=True, help_text="Where to buy this, if it's for sale."
            ),
        ),
    ]
