# Generated by Django 5.2.14 on 2026-07-01 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resources", "0010_alter_resource_purchase_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="resourcefile",
            name="purchase_url",
            field=models.URLField(
                blank=True, help_text="Where to buy this file/item, if it's for sale."
            ),
        ),
    ]
