# Generated by Django 5.2.14 on 2026-07-14 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resources", "0011_resourcefile_purchase_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="resourcefile",
            name="preview_image",
            field=models.ImageField(
                blank=True,
                help_text="Optional public preview image, shown inline for this file whatever its kind. Required to preview a locked file, whose real bytes stay private.",
                upload_to="resources/previews/",
            ),
        ),
    ]
