# Generated by Django 5.2.14 on 2026-06-07 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SiteConfiguration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                (
                    "seo_title",
                    models.CharField(
                        blank=True,
                        help_text="Overrides the HTML page title; defaults to the title.",
                        max_length=200,
                    ),
                ),
                (
                    "meta_description",
                    models.CharField(
                        blank=True,
                        help_text="Search-result snippet; ~150–160 chars ideal.",
                        max_length=300,
                    ),
                ),
                (
                    "canonical_url",
                    models.URLField(
                        blank=True, help_text="Optional canonical override."
                    ),
                ),
                ("og_title", models.CharField(blank=True, max_length=200)),
                ("og_description", models.CharField(blank=True, max_length=300)),
                (
                    "og_image",
                    models.ImageField(
                        blank=True,
                        help_text="Auto-generated when blank (where supported).",
                        upload_to="og/",
                    ),
                ),
                (
                    "noindex",
                    models.BooleanField(
                        default=False,
                        help_text="Exclude from sitemap and add a noindex tag.",
                    ),
                ),
            ],
            options={
                "verbose_name": "site configuration",
                "verbose_name_plural": "site configuration",
            },
        ),
    ]
