# Generated by Django 5.2.14 on 2026-06-12 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_site_configuration"),
    ]

    operations = [
        migrations.AddField(
            model_name="siteconfiguration",
            name="footer_tagline",
            field=models.CharField(
                default="Black & red since the rave.",
                help_text="The tagline shown in the site footer on every page.",
                max_length=200,
            ),
        ),
    ]
