# Generated by Django 5.2.14 on 2026-06-20 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_upload"),
    ]

    operations = [
        migrations.AddField(
            model_name="siteconfiguration",
            name="header_kicker_detail",
            field=models.CharField(
                default="official & fan archive",
                help_text="Homepage header kicker, second part (shown after the dash).",
                max_length=120,
            ),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="header_kicker_lead",
            field=models.CharField(
                default="Est. on the dancefloor",
                help_text="Homepage header kicker, first part (shown before the dash).",
                max_length=120,
            ),
        ),
    ]
