# Generated by Django 5.2.14 on 2026-06-20 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_siteconfiguration_header_kicker_detail_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="siteconfiguration",
            name="og_card_subtitle",
            field=models.CharField(
                blank=True,
                help_text="Optional smaller line under the headline on the generated OG image.",
                max_length=160,
            ),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="og_card_title",
            field=models.CharField(
                default="The fan source",
                help_text="Headline on the auto-generated homepage social-share (OG) image. Ignored if you upload your own image below.",
                max_length=120,
            ),
        ),
    ]
