# Generated by Django 5.2.14 on 2026-06-20 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_siteconfiguration_og_card_subtitle_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="siteconfiguration",
            name="og_card_image",
            field=models.ImageField(
                blank=True,
                help_text="Optional image composited into the right-hand square of the generated OG card (like album art on release cards). Leave blank for a text-only card.",
                upload_to="og/",
            ),
        ),
    ]
