# Generated by Django 5.2.14 on 2026-05-29 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.SlugField(blank=True, max_length=200, unique=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
            ],
            options={
                "verbose_name_plural": "categories",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.SlugField(blank=True, max_length=200, unique=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=100)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.SlugField(blank=True, max_length=200, unique=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                (
                    "seo_title",
                    models.CharField(
                        blank=True,
                        help_text="Overrides the <title>; defaults to the title.",
                        max_length=200,
                    ),
                ),
                (
                    "meta_description",
                    models.CharField(
                        blank=True,
                        help_text="Search-result snippet; ~150–160 chars ideal.",
                        max_length=300,
                    ),
                ),
                (
                    "canonical_url",
                    models.URLField(
                        blank=True, help_text="Optional canonical override."
                    ),
                ),
                ("og_title", models.CharField(blank=True, max_length=200)),
                ("og_description", models.CharField(blank=True, max_length=300)),
                (
                    "og_image",
                    models.ImageField(
                        blank=True,
                        help_text="Auto-generated when blank (where supported).",
                        upload_to="og/",
                    ),
                ),
                (
                    "noindex",
                    models.BooleanField(
                        default=False,
                        help_text="Exclude from sitemap and add a noindex tag.",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("excerpt", models.TextField(blank=True)),
                ("body", models.TextField(blank=True, help_text="Markdown.")),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                ("is_published", models.BooleanField(default=False)),
                ("cover_image", models.ImageField(blank=True, upload_to="blog/")),
                ("source_url", models.URLField(blank=True)),
                (
                    "import_confidence",
                    models.CharField(
                        choices=[
                            ("complete", "Complete"),
                            ("partial", "Partial"),
                            ("stub", "Stub"),
                        ],
                        default="complete",
                        max_length=20,
                    ),
                ),
                (
                    "manually_edited",
                    models.BooleanField(
                        default=False,
                        help_text="Set once edited by hand; protects from re-import.",
                    ),
                ),
                (
                    "categories",
                    models.ManyToManyField(
                        blank=True, related_name="posts", to="blog.category"
                    ),
                ),
                (
                    "tags",
                    models.ManyToManyField(
                        blank=True, related_name="posts", to="blog.tag"
                    ),
                ),
            ],
            options={
                "ordering": ["-published_at", "-created"],
            },
        ),
    ]
