# Generated by Django 5.2.14 on 2026-06-14 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_alter_post_seo_title"),
        ("discography", "0007_release_featured_artists"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="related_artists",
            field=models.ManyToManyField(
                blank=True,
                help_text="Artists to surface in this post's sidebar.",
                related_name="related_posts",
                to="discography.artist",
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="related_releases",
            field=models.ManyToManyField(
                blank=True,
                help_text="Releases to surface in this post's sidebar.",
                related_name="related_posts",
                to="discography.release",
            ),
        ),
    ]
