# Generated by Django 5.2.14 on 2026-06-15 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0003_post_related_artists_post_related_releases"),
        ("resources", "0006_resourcesubcategory_snippet_phrase"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="related_resources",
            field=models.ManyToManyField(
                blank=True,
                help_text="Resources to surface in this post's sidebar.",
                related_name="related_posts",
                to="resources.resource",
            ),
        ),
    ]
