# Generated by Django 5.2.14 on 2026-06-16 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0004_post_related_resources"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="credit",
            field=models.CharField(
                blank=True,
                help_text="Who tipped off / supplied this post; shown as a 'Thanks for this post to …' note at the top of the sidebar.",
                max_length=200,
                verbose_name="Thanks to",
            ),
        ),
    ]
