"""URL configuration for the editing CMS.

These routes exist only for the private/local editing environment (the Django admin
plus live previews). The public site is served as static files generated by
``manage.py build_site`` and does not run Django.
"""

from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path("admin/", admin.site.urls),
]

# Serve uploaded media during local editing/preview only.
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
