# Generated by Django 5.2.14 on 2026-05-29 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Page",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.SlugField(blank=True, max_length=200, unique=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                (
                    "seo_title",
                    models.CharField(
                        blank=True,
                        help_text="Overrides the <title>; defaults to the title.",
                        max_length=200,
                    ),
                ),
                (
                    "meta_description",
                    models.CharField(
                        blank=True,
                        help_text="Search-result snippet; ~150–160 chars ideal.",
                        max_length=300,
                    ),
                ),
                (
                    "canonical_url",
                    models.URLField(
                        blank=True, help_text="Optional canonical override."
                    ),
                ),
                ("og_title", models.CharField(blank=True, max_length=200)),
                ("og_description", models.CharField(blank=True, max_length=300)),
                (
                    "og_image",
                    models.ImageField(
                        blank=True,
                        help_text="Auto-generated when blank (where supported).",
                        upload_to="og/",
                    ),
                ),
                (
                    "noindex",
                    models.BooleanField(
                        default=False,
                        help_text="Exclude from sitemap and add a noindex tag.",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("body", models.TextField(blank=True, help_text="Markdown.")),
                (
                    "template_key",
                    models.CharField(
                        choices=[("standard", "Standard"), ("full", "Full width")],
                        default="standard",
                        max_length=20,
                    ),
                ),
                ("is_published", models.BooleanField(default=False)),
                (
                    "menu_order",
                    models.IntegerField(
                        default=0,
                        help_text="Order in the main navigation; 0 hides it from the menu.",
                    ),
                ),
            ],
            options={
                "ordering": ["menu_order", "title"],
            },
        ),
    ]
