# Generated by Django 5.2.14 on 2026-05-29 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="page",
            name="seo_title",
            field=models.CharField(
                blank=True,
                help_text="Overrides the HTML page title; defaults to the title.",
                max_length=200,
            ),
        ),
    ]
