# Generated by Django 5.2.14 on 2026-06-07 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0002_alter_page_seo_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="page",
            name="body",
            field=models.TextField(
                blank=True, help_text="Rich text (HTML), edited with TinyMCE."
            ),
        ),
    ]
